theme = "solarized-dark"
icons = "awesome5"

[[block]]
block = "pomodoro"
length = 25
break_length = 5
message = "Take a break!"
break_message = "Back to work!"
notifier = "notifysend"

[[block]]
block = "music"
buttons = ["play", "next"]
max_width = 45
#player = "lap"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}(avg) {min}(min) {max}(max)"
# chip = "*-isa-*"
chip = "k10temp-*"
warning = 65
info = 60
idle = 50

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 2.0
alert = 1.0

[[block]]
block = "disk_space"
path = "/mnt/elecom4tb"
alias = "bank"
info_type = "available"
unit = "GB"
interval = 20
warning = 2.0
alert = 1.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"
warning_mem = 90

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%Y/%m/%d %H:%M:%S"
